var benzinskepostaje = {
"type": "FeatureCollection",
"name": "benzinskepostaje",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Perišić Benz", "Adresa poduzeća": "Ulica Blage Zadre 2, Grude", "Djelatnost": "benzinska crpka, trgovina, kafić, praonica", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/perisicbenz.grude/", "Radno vrijeme": "pon.-ned.: 05:30-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4240294, 43.36686 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Perišić Benz 2", "Adresa poduzeća": "Ulica dr. Franje Tuđmana 122, Grude", "Djelatnost": "benzinska crpka, trgovina, kafić, praonica", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/perisicbenz.grude/", "Radno vrijeme": "pon.-ned.: 06:00-23:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4233015, 43.3668305 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Grafotisak", "Adresa poduzeća": "Ulica Gojka Šuška 7, Grude", "Djelatnost": "benzinska crpka, trgovina, kafić", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.grafotisak.com/", "Radno vrijeme": "pon.-ned.: 05:30-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4279572, 43.3698624 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Papić", "Adresa poduzeća": "Ulica dr. Franje Tuđmana 58, Grude", "Djelatnost": "benzinska crpka, trgovina, kafić", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.papic.ba/", "Radno vrijeme": "pon.-ned.: 06:00-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4182783, 43.3692413 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Auto Ana", "Adresa poduzeća": "Ulica hrvatskih branitelja 81, Grude", "Djelatnost": "benzinska crpka, trgovina, kafić, restoran, praonica, INA maziva", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.autoana.ba/", "Radno vrijeme": "pon.-ned.: 05:30-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4193671, 43.3618852 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Hifa Petrol", "Adresa poduzeća": "Vlašići 67, Sovići", "Djelatnost": "benzinska crpka, trgovina", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.hifapetrol.ba/", "Radno vrijeme": "pon.-ned.: 06:00-23:00" }, "geometry": { "type": "Point", "coordinates": [ 17.3179719, 43.409903 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Robiko", "Adresa poduzeća": "Plavilo 1, Drinovci", "Djelatnost": "benzinska crpka, trgovina, kafić", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/robiko_bih/", "Radno vrijeme": "pon.-ned.: 05:00-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.3145709, 43.3733177 ] } },
{ "type": "Feature", "properties": { "Naziv poduzeća": "Benzinska postaja Tioil", "Adresa poduzeća": "Donja Mala 15, Gorica", "Djelatnost": "benzinska crpka, trgovina", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://tioil.com/", "Radno vrijeme": "pon.-ned.: 06:00-23:00" }, "geometry": { "type": "Point", "coordinates": [ 17.2773321, 43.4219142 ] } }
]
}
