var crkve = {
"type": "FeatureCollection",
"name": "crkve",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Katarine Aleksandrijske", "Župa": "Grude", "Mjesto": "Grude (Gomilice)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1895.", "Web-stranica": "nema", "Značaj": "Površinski i brojem vjernika najveća župa Općine Grude." }, "geometry": { "type": "Point", "coordinates": [ 17.4097041, 43.374663 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Josipa", "Župa": "Tihaljina", "Mjesto": "Puteševica", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1989.", "Web-stranica": "https://www.facebook.com/zupa.tihaljina/?locale=hr_HR", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.3255921, 43.3118817 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Stjepana Prvomučenika (od Imote)", "Župa": "Gorica-Sovići", "Mjesto": "Gorica (Grabarje)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1968.", "Web-stranica": "https://zupagoricasovici.info/", "Značaj": "Najstarija župa Imotske krajine (i Općine Grude). Oko 100 m jugozapadno nalazi se jedna od najstarijih crkava u Hrvata, stara crkva sv. Stjepana Prvomučenika od Imote. Nova crkva izgrađena je zbog potreba župe i povećanja broja vjernika. Istovremeno, stara crkva služi kao važno misište i spomenik cijeloga grudskog kraja." }, "geometry": { "type": "Point", "coordinates": [ 17.2917833, 43.4200636 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Stara crkva sv. Stjepana Prvomučenika (od Imote)", "Župa": "Gorica-Sovići", "Mjesto": "Gorica (Grabarje)", "Vrsta crkve": "stara župna crkva", "Godina izgradnje": "1856.", "Web-stranica": "https://zupagoricasovici.info/", "Značaj": "Najstarija župa Imotske krajine (i Općine Grude). Jedna od najstarijih crkava rimske pokrajine Dalmacije (V. stoljeće) te u Hrvata (IX. stoljeće), središte Imotske krajine i jedina imotska crkva do rušenja od strane Turaka 1647. Patron župe uzdignut je na čast zaštitnika cijele Imotske krajine te stoga i danas nosi naslov ''crkva sv. Stipana Prvomučenika od Imote'' (suzaštitnik uz BDM od Anđela po oslobođenju Imotske krajine od Turaka 2. kolovoza 1717.). Dva puta rušena i tri puta građena." }, "geometry": { "type": "Point", "coordinates": [ 17.2900457, 43.4194866 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkvica sv. Ilije proroka", "Župa": "Tihaljina", "Mjesto": "Tihaljina (Nezdravica)", "Vrsta crkve": "kapelica", "Godina izgradnje": "1889.", "Web-stranica": "https://www.facebook.com/zupa.tihaljina/?locale=hr_HR", "Značaj": "Sv. Ilija slavi se kao zaštitnik župe Tihaljina još od njezina osnutka 1889., a od 1938. kao suzaštitnik jer je otad patron župe Bezgrešno začeće BDM." }, "geometry": { "type": "Point", "coordinates": [ 17.3907649, 43.3136177 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva Bezgrješnog začeća Blažene Djevice Marije", "Župa": "Tihaljina", "Mjesto": "Tihaljina (Nezdravica)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1938.", "Web-stranica": "https://www.facebook.com/zupa.tihaljina/?locale=hr_HR", "Značaj": "Površinski najveća crkva u Općini Grude." }, "geometry": { "type": "Point", "coordinates": [ 17.3905122, 43.3138785 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Ante", "Župa": "Raskrižje", "Mjesto": "Cerov Dolac", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1971.", "Web-stranica": "https://www.facebook.com/zuparaskrizje/?locale=hr_HR", "Značaj": "Župa je dobila ime po svom prostornom smještaju na \"raskrižju\" sela Cerov Dolac (u kojem se crkva nalazi), Pogane Vlake i Borajne koja i čine župu." }, "geometry": { "type": "Point", "coordinates": [ 17.4425641, 43.3281913 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Ivana Krstitelja", "Župa": "Ružići", "Mjesto": "Ružići (Žlibina)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1934.", "Web-stranica": "https://zupa-ruzici.com/", "Značaj": "Najstarija aktivna župa u Općini Grude (od 1768.)" }, "geometry": { "type": "Point", "coordinates": [ 17.3974273, 43.3439871 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Jure", "Župa": "Grude", "Mjesto": "Dragićina", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "2000.", "Web-stranica": "nema", "Značaj": "Crkva je izgrađena 2000. na mjestu stare kapelice podignute u čast sv. Jure 1925. godine." }, "geometry": { "type": "Point", "coordinates": [ 17.4491336, 43.3519382 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Nikole Tavelića", "Župa": "Ružići", "Mjesto": "Ružići (Marića Strana)", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1969.", "Web-stranica": "https://zupa-ruzici.com/", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.4298322, 43.3449405 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Zavjetna crkva sv. Izidora", "Župa": "Grude", "Mjesto": "Cere", "Vrsta crkve": "zavjetna kapelica", "Godina izgradnje": "1937.", "Web-stranica": "nema", "Značaj": "Podignuta u čast sv. Izidora Seljaka s nakanom boljeg uroda zemlje." }, "geometry": { "type": "Point", "coordinates": [ 17.3967631, 43.3889554 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Ante", "Župa": "Drinovci", "Mjesto": "Drinovačko Brdo", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1950.", "Web-stranica": "https://www.facebook.com/zupa.drinovci/", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.3025259, 43.3294346 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Luke", "Župa": "Drinovci", "Mjesto": "Blaževići", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1988.", "Web-stranica": "https://www.facebook.com/zupa.drinovci/", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.3510214, 43.3759139 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Terezije od Djeteta Isusa", "Župa": "Ledinac", "Mjesto": "Ledinac", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1930.", "Web-stranica": "https://www.zupaledinac.com/", "Značaj": "Najstarija crkva na području bivše Jugoslavije i jedna od najstarijih u svijetu općenito podignutih u čast sv. Terezije od Djeteta Isusa (kanonizirana 1925.). Prethodno je postojala kao župa Svetoga Križa (1873.-1878.)." }, "geometry": { "type": "Point", "coordinates": [ 17.4874644, 43.3445712 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Mihovila Arkanđela", "Župa": "Drinovci", "Mjesto": "Drinovci (Središte)", "Vrsta crkve": "župna crkva", "Godina izgradnje": "1894.", "Web-stranica": "https://www.facebook.com/zupa.drinovci/", "Značaj": "U vrijeme gradnje, najveća crkva na području Bosne i Hercegovine (nakon katedrale Presvetog Srca Isusova u Sarajevu)." }, "geometry": { "type": "Point", "coordinates": [ 17.3233425, 43.3595655 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Petra i Pavla", "Župa": "Gorica-Sovići", "Mjesto": "Sovići (Pejića Draga)", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1970.", "Web-stranica": "https://zupagoricasovici.info/", "Značaj": "Izgrađena na mjestu stare kapelice iz 1937. godine." }, "geometry": { "type": "Point", "coordinates": [ 17.3397424, 43.3996044 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Marka", "Župa": "Raskrižje", "Mjesto": "Borajna", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1993.", "Web-stranica": "https://www.facebook.com/zuparaskrizje/?locale=hr_HR", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.4737338, 43.3076766 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Petra", "Župa": "Drinovci", "Mjesto": "Drinovci (Ploca-Bili Greb)", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1971.", "Web-stranica": "https://www.facebook.com/zupa.drinovci/", "Značaj": "-" }, "geometry": { "type": "Point", "coordinates": [ 17.2881982, 43.3585711 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva sv. Petra i Pavla", "Župa": "Grljevići", "Mjesto": "Borajna", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1995.", "Web-stranica": "nema", "Značaj": "Crkva pripada župi Grljevići (Grad Ljubuški)." }, "geometry": { "type": "Point", "coordinates": [ 17.4864365, 43.2999684 ] } },
{ "type": "Feature", "properties": { "Naziv crkve": "Crkva Velike Gospe", "Župa": "Poljica Vrgorska", "Mjesto": "Jabuka-Mijaca", "Vrsta crkve": "filijalna crkva", "Godina izgradnje": "1876.", "Web-stranica": "https://smn.hr/poljica-vrgorska", "Značaj": "Izgrađena je na području Općine Grude, no crkva pripada župi Poljica Vrgorska (Grad Vrgorac). Koriste ju i stanovnici Jabuke zbog veće udaljenosti župne crkve u Tihaljini." }, "geometry": { "type": "Point", "coordinates": [ 17.3165633, 43.2942264 ] } }
]
}