var granicniprijelazi = {
"type": "FeatureCollection",
"name": "granicniprijelazi",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv ustanove": "Granični prijelaz Gorica", "Nadležna ustanova": "Granična policija BiH", "Razina uprave": "državna uprava", "Napomena": "Granični prijelaz otvoren je neprekidno.", "Web-stranica": "https://www.granpol.gov.ba/", "Mjesto": "Gorica (Donja Mala)", "Vrsta prijelaza": "za međunarodni promet", "Povezani prijelaz": "Vinjani Donji, Hrvatska (EU)", "Značaj": "Granični prijelaz datira iz XVIII. stoljeća, kad je Imotska krajina podijeljena na dva dijela: mletački dio (područje danas zvano Imotskom krajinom) te osmanski dio (Imotsku bekiju, koja obuhvaća područje Posušja i Gruda). U narodu se često naziva \"najneprirodnijom granicom na svitu\".", "Radno vrijeme": "pon.-ned.: 00:00-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.2755473, 43.4220332 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Granični prijelaz Drinovci", "Nadležna ustanova": "Granična policija BiH", "Razina uprave": "državna uprava", "Napomena": "Granični prijelaz samo za pogranični promet. U ljetnom razdoblju radi neprekidno kao prijelaz za međunarodni promet putnika u pograničnom prostoru.", "Web-stranica": "https://www.granpol.gov.ba/", "Mjesto": "Drinovci (Sebišina)", "Vrsta prijelaza": "za pogranični promet", "Povezani prijelaz": "Runovići (Sebišina), Hrvatska (EU)", "Značaj": "Granični prijelaz datira iz XVIII. stoljeća, kad je Imotska krajina podijeljena na dva dijela: mletački dio (područje danas zvano Imotskom krajinom) te osmanski dio (Imotsku bekiju, koja obuhvaća područje Posušja i Gruda). U narodu se često naziva \"najneprirodnijom granicom na svitu\".", "Radno vrijeme": "pon.-ned.: 06:00-22:00; ljeti, pon.-ned.: 00:00-24:00 (vidi napomenu)" }, "geometry": { "type": "Point", "coordinates": [ 17.2723341, 43.3625388 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Granični prijelaz Drinovačko Brdo", "Nadležna ustanova": "Granična policija BiH", "Razina uprave": "državna uprava", "Napomena": "Granični prijelaz samo za pogranični promet. U ljetnom razdoblju radi neprekidno i kao prijelaz za međunarodni promet putnika u pograničnom prostoru.", "Web-stranica": "https://www.granpol.gov.ba/", "Mjesto": "Drinovačko Brdo", "Vrsta prijelaza": "za pogranični promet", "Povezani prijelaz": "Slivno, Hrvatska (EU)", "Značaj": "Granični prijelaz datira iz XVIII. stoljeća, kad je Imotska krajina podijeljena na dva dijela: mletački dio (područje danas zvano Imotskom krajinom) te osmanski dio (Imotsku bekiju, koja obuhvaća područje Posušja i Gruda). U narodu se često naziva \"najneprirodnijom granicom na svitu\".", "Radno vrijeme": "pon.-ned.: 06:00-22:00; ljeti, pon.-ned.: 00:00-24:00 (vidi napomenu)" }, "geometry": { "type": "Point", "coordinates": [ 17.2983825, 43.3190969 ] } }
]
}