var javnauprava = {
"type": "FeatureCollection",
"name": "javnauprava",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv ustanove": "Matični ured Drinovci", "Adresa ustanove": "Središte 32, Drinovci", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Općina Grude, Služba za opću upravu, branitelje i društvene djelatnosti", "Razina uprave": "mjesna razina", "Napomena": "Ne radi svaki dan u tjednu. Rad ureda organiziran je prema rasporedu jednog matičara koji pokriva više matičnih ureda.", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 08.00-14:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3231283, 43.3607815 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ministarstvo hrvatskih branitelja iz Domovinskog rata", "Adresa ustanove": "Ulica Stjepana Radića 1, Grude", "Vrsta ustanove": "ministarstvo, javna uprava", "Nadređena ustanova": "Županija zapadnohercegovačka, Vlada ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sjedište ministarstva pri Vladi Županije zapadnohercegovačke. Služba za branitelje nalazi se u sklopu zgrade općine.", "Web-stranica": "http://www.mbzzh.ba", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4140644, 43.3714974 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Općina Grude", "Adresa ustanove": "Ulica fra Gabre Grubišića 4, Grude", "Vrsta ustanove": "tijelo mjesne samouprave", "Nadređena ustanova": "Županija zapadnohercegovačka", "Razina uprave": "mjesna razina", "Napomena": "U okviru općinske uprave djeluju tri službe: Služba za opću upravu, branitelje iz Domovinskog rata i društvene djelatnosti, Služba za prostorno uređenje, imovinsko-pravne i katastarske poslove te Služba za gospodarstvo, financije, inspekcijske poslove i civilnu zaštitu. U okviru Općine nalaze se uredi koji pružaju usluge građanima.", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4122196, 43.3731646 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ministarstvo zdravstva, rada, obitelji i socijalne politike", "Adresa ustanove": "Ulica Stjepana Radića 1, Grude", "Vrsta ustanove": "ministarstvo, javna uprava", "Nadređena ustanova": "Županija zapadnohercegovačka, Vlada ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sjedište ministarstva pri Vladi Županije zapadnohercegovačke.", "Web-stranica": "https://www.mzrss-zzh.com", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4140294, 43.3714091 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Matični ured Donji Mamići", "Adresa ustanove": "Ledinac 101, Donji Mamići", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Općina Grude, Služba za opću upravu, branitelje i društvene djelatnosti", "Razina uprave": "mjesna razina", "Napomena": "Ne radi svaki dan u tjednu. Rad ureda organiziran je prema rasporedu jednog matičara koji pokriva više matičnih ureda.", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 08.00-14:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4858288, 43.3456113 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Matični ured Grude", "Adresa ustanove": "Ulica fra Gabre Grubišića 4, Grude", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Općina Grude, Služba za opću upravu, branitelje i društvene djelatnosti", "Razina uprave": "mjesna razina", "Napomena": "Središnji matični ured Općine Grude.", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4119038, 43.3732546 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Matični ured Sovići", "Adresa ustanove": "Dom 14, Sovići", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Općina Grude, Služba za opću upravu, branitelje i društvene djelatnosti", "Razina uprave": "mjesna razina", "Napomena": "-", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 08.00-14:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3106066, 43.413775 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "J. P. Komunalno Grude", "Adresa ustanove": "Ulica Republike Hrvatske 15/A, Grude", "Vrsta ustanove": "javno komunalno poduzeće", "Nadređena ustanova": "Općina Grude", "Razina uprave": "mjesna razina", "Napomena": "-", "Web-stranica": "https://komunalno-grude.ba", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4124769, 43.3726742 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Centar za socijalni rad", "Adresa ustanove": "Ulica Republike Hrvatske 15/B, Grude", "Vrsta ustanove": "ustanova za socijalnu zaštitu", "Nadređena ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Nadležno je Ministarstvo zdravstva, rada, obitelji i socijalne politike sa sjedištem u Grudama. ", "Web-stranica": "https://www.mzrss-zzh.com", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4123153, 43.3727068 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Mirovinsko i invalidsko osiguranje - ispostava Grude", "Adresa ustanove": "Ulica dr. Franje Tuđmana 83/B, Grude", "Vrsta ustanove": "ustanova za mirovinsko i invalidsko osiguranje", "Nadređena ustanova": "Federalni zavod za mirovinsko i invalidsko osiguranje FBiH", "Razina uprave": "federalna razina", "Napomena": "Na županijskoj razini nadležna je uprava u Ljubuškom.", "Web-stranica": "https://www.fzmiopio.ba", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4201315, 43.3684355 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Porezna uprava - ispostava Grude", "Adresa ustanove": "Ulica dr. Franje Tuđmana 85/B, Grude", "Vrsta ustanove": "ustanova za poreznu administraciju", "Nadređena ustanova": "Porezna uprava FBiH", "Razina uprave": "federalna razina", "Napomena": "Na županijskoj razini nadležna je uprava u Ljubuškom.", "Web-stranica": "https://www.pufbih.ba", "Radno vrijeme": "pon.-pet.: 08:00-16:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4207517, 43.3682294 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "J. U. Vrilo", "Adresa ustanove": "Trg Herceg Bosne 3, Grude", "Vrsta ustanove": "ustanova za komunalne i infrastrukturne djelatnost", "Nadređena ustanova": "Općina Grude", "Razina uprave": "mjesna razina", "Napomena": "-", "Web-stranica": "nema", "Radno vrijeme": "nepoznato" }, "geometry": { "type": "Point", "coordinates": [ 17.4195472, 43.3642407 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Odsjek upravnih poslova", "Adresa ustanove": "Trg Herceg Bosne 1, Grude", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Ministarstvo unutarnjih poslova ŽZH", "Razina uprave": "županijska razina", "Napomena": "-", "Web-stranica": "https://www.mupzzh.ba/", "Radno vrijeme": "pon.-sri., pet.: 08:00-16:00; čet.: 08:00-18:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4189519, 43.3643343 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Zavod za zdravstveno osiguranje ŽZH", "Adresa ustanove": "Trg Herceg Bosne 1, Grude", "Vrsta ustanove": "ured za zdravstveno osiguranje", "Nadređena ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Mjesni ured (ispostava Grude) nalazi se na Boboški.", "Web-stranica": "https://zzozzh.com", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.41907, 43.3644809 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ured za zdravstveno osiguranje, ispostava Grude", "Adresa ustanove": "Ulica dr. Franje Tuđmana 85/A, Grude", "Vrsta ustanove": "ured za zdravstveno osiguranje", "Nadređena ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Središnji ured pri ministarstvu nalazi se na Bilom Brigu.", "Web-stranica": "https://zzozzh.com", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4203983, 43.3683243 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Matični ured Tihaljina", "Adresa ustanove": "Nezdravica 58, Tihaljina", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Općina Grude, Služba za opću upravu, branitelje i društvene djelatnosti", "Razina uprave": "mjesna razina", "Napomena": "Ne radi svaki dan u tjednu. Rad ureda organiziran je prema rasporedu jednog matičara koji pokriva više matičnih ureda.", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 08.00-14:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3865755, 43.3148358 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Javnobilježnički ured Grude", "Adresa ustanove": "Ulica hrvatskih branitelja 12, Grude", "Vrsta ustanove": "javnobilježnički ured", "Nadređena ustanova": "Ministarstvo pravosuđa, uprave i digitalne transformacije ŽZH", "Razina uprave": "županijska razina", "Napomena": "-", "Web-stranica": "https://www.mpiuzzh.gov.ba/", "Radno vrijeme": "pon.-pet.: 08:00-16:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4229428, 43.3649356 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Matični ured Ružići", "Adresa ustanove": "Stočić 13/A, Ružići", "Vrsta ustanove": "upravni ured", "Nadređena ustanova": "Općina Grude, Služba za opću upravu, branitelje i društvene djelatnosti", "Razina uprave": "mjesna razina", "Napomena": "Ne radi svaki dan u tjednu. Rad ureda organiziran je prema rasporedu jednog matičara koji pokriva više matičnih ureda.", "Web-stranica": "https://grude.info", "Radno vrijeme": "pon.-pet.: 08.00-14:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4120481, 43.3394619 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Služba za zapošljavanje ŽZH", "Adresa ustanove": "Trg Herceg Bosne 1, Grude", "Vrsta ustanove": "ured za zapošljavanje", "Nadređena ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sjedište Službe u Županiji zapadnohercegovačkoj.", "Web-stranica": "https://szz-zzh.ba/", "Radno vrijeme": "pon.-pet.: 08:00-16:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4191679, 43.3644479 ] } }
]
}
