var kulturneustanove = {
"type": "FeatureCollection",
"name": "kulturneustanove",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv ustanove": "Gradska knjižnica Grude", "Adresa ustanove": "Park hrvatskih velikana 3, Grude", "Vrsta ustanove": "knjižnica", "Napomena": "Djelatnost knjižnice je nabava, obrada, pohrana, čuvanje i zaštita knjižnične građe, pružanje pristupa informacijskim izvorima, pomoć u radu s novim tehnologijama te organiziranje najrazličitijih edukacija i radionica za sve dobne skupine.", "Web-stranica": "https://kd-grude.info/", "Nadležna ustanova": "Kulturni dom Antun Branko Šimić", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4148541, 43.3723071 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Kulturni dom Antun Branko Šimić", "Adresa ustanove": "Park hrvatskih velikana 3, Grude", "Vrsta ustanove": "kulturni centar", "Napomena": "Kulturni dom promiče kulturu, očuvanje tradicije i poticanje kreativnog izražavanja. Svrha ustanove je očuvati i razvijati kulturni identitet, stvarati prilike za umjetnički izričaj te pružiti prostor za dijalog i suradnju.", "Web-stranica": "https://kd-grude.info/", "Nadležna ustanova": "Općina Grude", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4146527, 43.3723601 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Matica hrvatska - ogranak Grude", "Adresa ustanove": "Park hrvatskih velikana 3, Grude", "Vrsta ustanove": "kulturna organizacija", "Napomena": "Ogranak u Grudama osnovan je 1991. godine. Organizira i suorganizira brojne manifestacije na području Općine Grude i šire. Godišnje tiska svoj godišnjak ''Susreti''.", "Web-stranica": "https://maticahrvatska-grude.org/", "Nadležna ustanova": "Matica hrvatska (središnjica Zagreb)", "Radno vrijeme": "pon.-pet.: 08:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.414801, 43.3724543 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Kinodvorana Grude", "Adresa ustanove": "Ulica Republike Hrvatske 22, Grude", "Vrsta ustanove": "dvorana", "Napomena": "Dvorana broji 132 sjedeća mjesta. Koristi se za promocije, predstave, predavanja, radionice i sl.", "Web-stranica": "https://kd-grude.info/", "Nadležna ustanova": "Kulturni dom Antun Branko Šimić", "Radno vrijeme": "pon.-pet.: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4119372, 43.3730035 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Hrvatska franjevačka arheološka zbirka ''Sv. Stjepan'' Gorica", "Adresa ustanove": "Grabarje 19, Gorica", "Vrsta ustanove": "arheološka zbirka", "Napomena": "Zbirka čuva bogatu kulturno-povijesnu baštinu, posebice ranokršćanske nalaze s područja stare Imote. Brojni dokazi pronađeni u groblju Šamatorje i na području stare župne crkve upućuju da je ovo područje kroz povijest bilo središte stare hrvatske županije Imote, nakon čega središte postaje Imotski. Arheološki nalazi iz 1995. i kasnije predstavljaju vrijedan biser povijesti Općine Grude.", "Web-stranica": "https://www.facebook.com/hfazsvstjepana?locale=hr_HR", "Nadležna ustanova": "Župa Gorica-Sovići", "Radno vrijeme": "prema dogovoru uz najavu u župnom uredu" }, "geometry": { "type": "Point", "coordinates": [ 17.2911534, 43.4195177 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Radio Grude", "Adresa ustanove": "Ulica viteza Ranka Bobana 1, Grude", "Vrsta ustanove": "radio postaja", "Napomena": "Radio se može slušati na frekvencijama 95.5 (Grude i susjedne općine) i 90.9 (općine udaljenije od Gruda) MHz. Pokrenut 1998. godine.", "Web-stranica": "https://radiogrude.net/", "Nadležna ustanova": "nema", "Radno vrijeme": "pon.-ned.: 08:00-20:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4150794, 43.3722039 ] } }
]
}
