var ljekarne = {
"type": "FeatureCollection",
"name": "ljekarne",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Ljubić", "Adresa ustanove": "Ulica hrvatskih branitelja 49, Grude", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "Ugovorna ljekarna ZZO ŽZH.", "Web-stranica": "https://ljekarnaljubic.ba/", "Radno vrijeme": "pon.-sub.: 08:00-21:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4221523, 43.363915 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Mirna", "Adresa ustanove": "Ulica dr. Franje Tuđmana 108, Grude", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "Ugovorna ljekarna ZZO ŽZH.", "Web-stranica": "https://www.instagram.com/ljekarnamirna/", "Radno vrijeme": "pon.-sub: 07:30-21:00; ned.: 08:00-12:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4222554, 43.3674583 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Biopharm-Grude", "Adresa ustanove": "Ulica Mate Bobana 9, Grude", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "Ugovorna ljekarna ZZO ŽZH.", "Web-stranica": "https://biopharm.ba/", "Radno vrijeme": "pon.-sub.: 07:30-20:30" }, "geometry": { "type": "Point", "coordinates": [ 17.4144911, 43.3718159 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Ljubić", "Adresa ustanove": "Dom 8, Sovići", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "Ugovorna ljekarna ZZO ŽZH.", "Web-stranica": "https://ljekarnaljubic.ba/", "Radno vrijeme": "pon.-sub.: 08:00-20:00" }, "geometry": { "type": "Point", "coordinates": [ 17.310704, 43.4137397 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Medikament", "Adresa ustanove": "Središte 33, Drinovci", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "-", "Web-stranica": "nema", "Radno vrijeme": "pon.-pet.: 07:00-16:00; sub.: 07:00-13:00" }, "geometry": { "type": "Point", "coordinates": [ 17.3231563, 43.3607072 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Biopharm-Grude II", "Adresa ustanove": "Ulica dr. Franje Tuđmana 51, Grude", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "Ugovorna ljekarna ZZO ŽZH.", "Web-stranica": "https://biopharm.ba/", "Radno vrijeme": "pon.-sub.: 07:30-20:30" }, "geometry": { "type": "Point", "coordinates": [ 17.4181137, 43.369763 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ljekarna Biopharm-Grude III", "Adresa ustanove": "Ulica hrvatskih branitelja 21, Grude", "Vrsta ustanove": "ljekarnička ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Napomena": "Ugovorna ljekarna ZZO ŽZH. Nalazi se u sklopu kompleksa Supernova.", "Web-stranica": "https://biopharm.ba/", "Radno vrijeme": "pon.-sub.: 07:30-20:30" }, "geometry": { "type": "Point", "coordinates": [ 17.4253018, 43.3648661 ] } }
]
}
