var prirodneznamenitosti = {
"type": "FeatureCollection",
"name": "prirodneznamenitosti",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Mjesto": "Drinovci (Krenica)", "Značaj": "Prema pučkoj predaji, žena bogataša Gavana nije primila sv. Petra te su se na njegovim dvorima stvorila jezera: Crveno i Modro jezero kod Imotskog, Krenica kraj Prološca, udubina Vrbina u Blaževićima te samo drinovačko jezero Krenica. Jezero je dužine 310 m i širine 270 m. Procjene dubine kreću se od 40 do 200 m. Voda jezera je čista.", "Naziv znamenitosti": "Jezero Krenica", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3327249, 43.3751553 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Blaževići", "Značaj": "Prema znanstvenim izvorima, jednakog postanka kao Modro, a posebice Crveno jezero kod Imotskog, ali bez vode na svom dnu. Prema pučkoj predaji, žena bogataša Gavana nije primila sv. Petra te su se na njegovim dvorima stvorila jezera: Crveno i Modro jezero kod Imotskog, Krenica kraj Prološca, Krenica u Drinovcima te sama udubina Vrbina.", "Naziv znamenitosti": "Udubina Vrbina", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3606832, 43.3693044 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Drinovci (Kamenice, Ploca, Prisoje) ", "Značaj": "Umjetno jezero na rijeci Matici. Izgrađeno za potrebe HE Peć Mlini na mjestu poniranja Matice, a napaja se vodom iz same rijeke te okolne vode iz Imotskog polja.", "Naziv znamenitosti": "Jezero Nuga", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3115153, 43.3572582 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Drinovci (Kamenice, Ploca)", "Značaj": "Imotsko-bekijska ikavica jednostavno ju naziva Rika. Izvire kao Vrljika u Prološcu iz pet jezera te nastavlja put prema Kamenmostu gdje mijenja ime u Matica te se ulijeva u jezero Nuga. Ova ponornica na putu od Posušja, preko Imotskog, Drinovaca i Tihaljine i sve do Čapljine mijenja ime devet puta (Culuša-Ričina-Brina-Suvaja-Vrljika-Matica-Tihaljina-Mlade-Trebižat).", "Naziv znamenitosti": "Ušće rijeke Matice", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3068724, 43.356728 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Drinovci (Peć Mlini)", "Značaj": "Imotsko-bekijska ikavica jednostavno ju naziva Rika. Ponire u jezeru Nuga te opet izvire u Peć Mlinima. Mijenja ime u Mlade kod Klobuka. Ova ponornica na putu od Posušja, preko Imotskog, Drinovaca i Tihaljine i sve do Čapljine mijenja ime devet puta (Culuša-Ričina-Brina-Suvaja-Vrljika-Matica-Tihaljina-Mlade-Trebižat).", "Naziv znamenitosti": "Izvor rijeke Tihaljine", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3238667, 43.3365531 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Grudsko Vrilo", "Značaj": "Glavno vodocrpilište za područje Općine Grude.", "Naziv znamenitosti": "Izvor Grudskog Vrila", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3688177, 43.3902534 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Ledinac-Podledinac", "Značaj": "Najistočnija točka Imotskog polja, lokalitet Baran, imenovanom po brojnim barama koje se pojave nakon obilnijih kiša, smještena ispod brda Stranjik. Najzapadnija točka je Prološko Blato u Postranju kod Prološca, također poplavljeno, močvarno područje.", "Naziv znamenitosti": "Krajnji istok Imotskog polja", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.471329, 43.3398969 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Tihaljina (Podgradina)", "Značaj": "Slapovi Jašine na rijeci Tihaljini.", "Naziv znamenitosti": "Slapovi Jašine", "Vrsta znamenitosti": "prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3563748, 43.3186358 ] } },
{ "type": "Feature", "properties": { "Mjesto": "Drinovci (Peć Mlini)", "Značaj": "Jedno od najznačajnijih prapovijesnih nalazišta Imote te Bosne i Hercegovine. Istraživanja u Ravlića pećini iz 1980.-ih dala su brojne dokaze o životu u mlađem kamenom dobu. Pećina ima dužinu od 145 m i visinu 5-20 m (istraženi dio).", "Naziv znamenitosti": "Ravlića pećina", "Vrsta znamenitosti": "kulturno-povijesno i prirodno obilježje" }, "geometry": { "type": "Point", "coordinates": [ 17.3230988, 43.3390771 ] } }
]
}