var skole = {
"type": "FeatureCollection",
"name": "skole",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Godina osnutka": "1900.", "Napomena": "Učenici mogu pohađati školu od I. do IX. razreda. Srednjoškolsko obrazovanje mogu nastaviti u Grudama, a vrlo često i u Imotskom.", "Naziv ustanove": "Osnovna škola Antuna Branka i Stanislava Šimića, Drinovci", "Vrsta ustanove": "osnovna škola", "Adresa ustanove": "Središte 25, Drinovci", "Matična ustanova": "središnja škola", "Web-stranica": "https://os-drinovci.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3224016, 43.3608272 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1905.", "Napomena": "Učenici mogu pohađati školu od I. do IX. razreda. Srednjoškolsko obrazovanje mogu nastaviti u Grudama, a vrlo često i u Imotskom.", "Naziv ustanove": "Osnovna škola Ruđera Boškovića, Grude", "Vrsta ustanove": "osnovna škola", "Adresa ustanove": "Ulica Ivana Alilovića 1, Grude", "Matična ustanova": "središnja škola", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.4159493, 43.3694618 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1964.", "Napomena": "Učenici mogu pohađati školu od I. do IV. razreda, uz mogućnost izbora gimnazijskog i strukovnih programa.", "Naziv ustanove": "Srednja škola Antuna Branka Šimića, Grude", "Vrsta ustanove": "srednja škola", "Adresa ustanove": "Ulica dr. Franje Tuđmana 14, Grude", "Matična ustanova": "središnja škola", "Web-stranica": "https://ss-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.4157919, 43.3707049 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole (VI.-IX. razred) nastavljaju u matičnoj školi u Drinovcima.", "Naziv ustanove": "Područna škola Antuna Branka i Stanislava Šimića, Tihaljina-Drinovci", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Nezdravica 17, Tihaljina", "Matična ustanova": "OŠ Drinovci", "Web-stranica": "https://os-drinovci.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3913026, 43.3121643 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1973.", "Napomena": "Učenici mogu pohađati školu od I. do IX. razreda. Srednjoškolsko obrazovanje mogu nastaviti u Grudama, a vrlo često i u Imotskom.", "Naziv ustanove": "Osnovna škola fra Stipana Vrljića, Sovići", "Vrsta ustanove": "osnovna škola", "Adresa ustanove": "Vlašići 35, Sovići", "Matična ustanova": "središnja škola", "Web-stranica": "https://os-sovici.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3219299, 43.4057312 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Grudama.", "Naziv ustanove": "Područna škola Ruđera Boškovića, Ledinac-Grude", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Ledinac 101, Donji Mamići", "Matična ustanova": "OŠ Grude", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.485789, 43.3458342 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Grudama.", "Naziv ustanove": "Područna škola Ruđera Boškovića, Vrućice-Grude", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Vrućice 58, Vrućice", "Matična ustanova": "OŠ Grude", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3733632, 43.386718 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Drinovcima.", "Naziv ustanove": "Područna škola Antuna Branka i Stanislava Šimića, Drinovačko Brdo-Drinovci", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Drinovačko Brdo 67, Drinovačko Brdo", "Matična ustanova": "OŠ Drinovci", "Web-stranica": "https://os-drinovci.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3025748, 43.3192053 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Sovićima.", "Naziv ustanove": "Područna škola fra Stipana Vrljića, Gorica-Sovići", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Jurinovac 11, Gorica", "Matična ustanova": "OŠ Sovići", "Web-stranica": "https://os-sovici.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.287001, 43.4202673 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Grudama.", "Naziv ustanove": "Područna škola Ruđera Boškovića, Dragićina-Grude", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Dragićina 116, Dragićina", "Matična ustanova": "OŠ Grude", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.4486239, 43.3517857 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Grudama.", "Naziv ustanove": "Područna škola Ruđera Boškovića, Pogana Vlaka-Grude", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Pogana Vlaka 96, Pogana Vlaka", "Matična ustanova": "OŠ Grude", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.4502513, 43.3338251 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Grudama.", "Naziv ustanove": "Područna škola Ruđera Boškovića, Ružići-Grude", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Žlibina 53, Ružići", "Matična ustanova": "OŠ Grude", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3960147, 43.3462437 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1950.-ih", "Napomena": "Učenici mogu pohađati školu od I. do V. razreda (razredna nastava). Više razrede osnovne škole, VI.-IX. razreda, nastavljaju u matičnoj školi u Grudama.", "Naziv ustanove": "Područna škola Ruđera Boškovića, Borajna-Grude", "Vrsta ustanove": "područna osnovna škola", "Adresa ustanove": "Borajna 22, Borajna", "Matična ustanova": "OŠ Grude", "Web-stranica": "https://os-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.4795791, 43.3025661 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "1995.", "Napomena": "U okviru škole djeluju osnovna (od 1995.) i srednja glazbena škola (od 2020.)", "Naziv ustanove": "Glazbena škola Grude", "Vrsta ustanove": "glazbena škola", "Adresa ustanove": "Ulica dr. Franje Tuđmana 14, Grude", "Matična ustanova": "središnja škola", "Web-stranica": "https://gs-grude.skole.sum.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.4158147, 43.3703175 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2024.", "Napomena": "Centar pruža potporu u razvoju i jačanju potencijala djece i mladih te sprječavanju novih i težih poteškoća.", "Naziv ustanove": "Edukacijsko-rehabilitacijski centar Ivan Pavao II.", "Vrsta ustanove": "centar za djecu i mlade s teškoćama u razvoju", "Adresa ustanove": "Vlašići 35/A, Sovići", "Matična ustanova": "nema", "Web-stranica": "https://www.instagram.com/p/DQHEndHjKUl/" }, "geometry": { "type": "Point", "coordinates": [ 17.3227362, 43.4055953 ] } }
]
}