var smjestaji = {
"type": "FeatureCollection",
"name": "smjestaji",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv objekta": "Hotel Otok", "Adresa objekta": "Ulica fra Gabre Grubišića 21, Grude", "Vrsta smještaja": "hotel", "Radno vrijeme": "pon.-ned.: 07:00-23:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.hotelotok.net/hr/" }, "geometry": { "type": "Point", "coordinates": [ 17.4074696, 43.3786629 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Hotel Kod Barića", "Adresa objekta": "Ulica dr. Franje Tuđmana 114, Grude", "Vrsta smještaja": "hotel", "Radno vrijeme": "pon.-ned.: 07:00-23:00", "Parkiralište": "Vlastito parkiralište i garaža.", "Web-stranica": "https://kodbarica.com/rooms/" }, "geometry": { "type": "Point", "coordinates": [ 17.4225714, 43.3670499 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Motel Kiwi", "Adresa objekta": "Marića Strana 57, Ružići", "Vrsta smještaja": "motel", "Radno vrijeme": "pon.-ned.: 07:00-23:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.motelkiwi.com/index.php/motel" }, "geometry": { "type": "Point", "coordinates": [ 17.4301476, 43.3401128 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Hotel Marića Gaj", "Adresa objekta": "Marića Strana 62, Ružići", "Vrsta smještaja": "hotel", "Radno vrijeme": "pon.-ned.: 07:00-23:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/maricagaj/" }, "geometry": { "type": "Point", "coordinates": [ 17.4324814, 43.3393784 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Gostinjska kuća Pezer", "Adresa objekta": "Živa Ljut 12, Ružići", "Vrsta smještaja": "apartman i konoba", "Radno vrijeme": "pon.-ned.: 07:00-23:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.facebook.com/konobapezer/?locale=hr_HR" }, "geometry": { "type": "Point", "coordinates": [ 17.4397456, 43.3218637 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Villa Medo", "Adresa objekta": "Središte 30, Drinovci", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "pon.-ned.: 10:00-15:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/holidayhomemedo/" }, "geometry": { "type": "Point", "coordinates": [ 17.3215584, 43.3608953 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Villa Braco", "Adresa objekta": "Dubrava 105, Drinovci", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "pon.-ned.: 10:00-15:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.3153042, 43.3771812 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Hotel Dado", "Adresa objekta": "Dubrava 41/A, Drinovci", "Vrsta smještaja": "hotel", "Radno vrijeme": "pon.-ned.: 10:00-23:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.hotel-dado.ba/" }, "geometry": { "type": "Point", "coordinates": [ 17.3057971, 43.3810715 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Villa Ivanovi dvori", "Adresa objekta": "Nezdravica 19, Tihaljina", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "pon.-ned.: 10:00-15:00", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/ivanovi_dvori/" }, "geometry": { "type": "Point", "coordinates": [ 17.3867219, 43.3106627 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Motel Dorin", "Adresa objekta": "Vlašići 63, Sovići", "Vrsta smještaja": "motel", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.31834, 43.4094373 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Villa Maca", "Adresa objekta": "Pejići 62, Sovići", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.3318817, 43.4049366 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Kuća Aronija", "Adresa objekta": "Grabarje 4, Gorica", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.2892423, 43.4211977 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Lea Lux", "Adresa objekta": "Ulica dr. Franje Tuđmana 1, Grude", "Vrsta smještaja": "apartman", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.4155326, 43.3716245 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Alpeza", "Adresa objekta": "Ulica viteza Ranka Bobana 1, Grude", "Vrsta smještaja": "apartman", "Radno vrijeme": "nepoznato", "Parkiralište": "Nema, koristiti obližnja parkirališta u Centru.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.4149509, 43.3721596 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Vukoja", "Adresa objekta": "Ulica Mate Bobana 16, Grude", "Vrsta smještaja": "apartman", "Radno vrijeme": "nepoznato", "Parkiralište": "Nema, koristiti obližnja parkirališta u Centru.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.4149529, 43.371594 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Centar", "Adresa objekta": "Ulica Mate Bobana 12, Grude", "Vrsta smještaja": "apartman", "Radno vrijeme": "nepoznato", "Parkiralište": "Nema, koristiti obližnja parkirališta u Centru.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.4145975, 43.3716305 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Žuta kuća", "Adresa objekta": "Pejića Draga BB, Sovići", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.3443893, 43.3996222 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Grude", "Adresa objekta": "Ulica dr. Franje Tuđmana 79, Grude", "Vrsta smještaja": "apartman", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.4199147, 43.3688976 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Apartman Vranješ", "Adresa objekta": "Ulica hrvatskih branitelja 75, Grude", "Vrsta smještaja": "apartman", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "nema" }, "geometry": { "type": "Point", "coordinates": [ 17.4197327, 43.3623882 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Villa Kamena", "Adresa objekta": "Podledinac 45, Donji Mamići", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/kuca_za_odmor_kamena/" }, "geometry": { "type": "Point", "coordinates": [ 17.4779745, 43.3234838 ] } },
{ "type": "Feature", "properties": { "Naziv objekta": "Villa Lea", "Adresa objekta": "Dragićina 27/A, Dragićina", "Vrsta smještaja": "kuća za odmor", "Radno vrijeme": "nepoznato", "Parkiralište": "Vlastito parkiralište.", "Web-stranica": "https://www.instagram.com/villa_leaa/" }, "geometry": { "type": "Point", "coordinates": [ 17.4364891, 43.3661283 ] } }
]
}
