var stomatoloskeustanove = {
"type": "FeatureCollection",
"name": "stomatoloskeustanove",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv ustanove": "Stomatološka ordinacija Apolonija", "Adresa ustanove": "Ulica Blage Zadre 15/B, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "https://www.instagram.com/apoloniagrude/", "Radno vrijeme": "pon.: 13:00-20:00; uto.-pet.: 09:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4263577, 43.3686331 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Stomatološka ordinacija Dent Estetica", "Adresa ustanove": "Ulica Andrijice Šimića 2, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "https://www.instagram.com/dentestetica_grude/?hl=hr", "Radno vrijeme": "pon., sri.: 13:00-20:00; uto., čet.-pet.: 08:00-15:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4158294, 43.3717761 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Zubni centar Zadro", "Adresa ustanove": "Bostan 2, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "https://zadro.online/", "Radno vrijeme": "pon.-pet.: 08:00-16:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4143809, 43.3713234 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Stomatološka ordinacija dr. Nediljka Grizelj", "Adresa ustanove": "Ulica Bili Brig 4, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "nema", "Radno vrijeme": "pon., sri.-čet.: 13:00-20:00; uto., pet.: 08:30-15:30" }, "geometry": { "type": "Point", "coordinates": [ 17.4197443, 43.3637151 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Stomatološka ordinacija dr. Ankica Šimić", "Adresa ustanove": "Ulica Republike Hrvatske 26/A, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "nema", "Radno vrijeme": "nepoznato" }, "geometry": { "type": "Point", "coordinates": [ 17.4114681, 43.3730489 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Stomatološka ordinacija dr. Ivana Galić", "Adresa ustanove": "Ulica hrvatskih branitelja 34, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "nema", "Radno vrijeme": "nepoznato" }, "geometry": { "type": "Point", "coordinates": [ 17.419587, 43.3628662 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Stomatološka ordinacija dr. Oliver Božić", "Adresa ustanove": "Ulica Bili Brig 4, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "nema, privatna ustanova", "Razina uprave": "-", "Web-stranica": "nema", "Radno vrijeme": "nepoznato" }, "geometry": { "type": "Point", "coordinates": [ 17.4199164, 43.3636361 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Dom zdravlja Grude (stomatologija)", "Adresa ustanove": "Ulica Mate Bobana 6, Grude", "Vrsta ustanove": "stomatološka ustanova", "Nadležna ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Web-stranica": "https://dzgrude.com/", "Radno vrijeme": "pon.-pet.: 07:00-20:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4141139, 43.3717358 ] } }
]
}
