var vrtici = {
"type": "FeatureCollection",
"name": "vrtici",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Godina osnutka": "1998.", "Naziv ustanove": "Dječji vrtić Grude", "Vrsta ustanove": "javni dječji vrtić", "Adresa ustanove": "Ulica Ivana Alilovića 3, Grude", "Matična ustanova": "središnja ustanova", "Web-stranica": "https://www.instagram.com/djecjivrticgrude/", "Radno vrijeme": "pon.-pet.: 07:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4158274, 43.3690211 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2024.", "Naziv ustanove": "Dječji vrtić Grude, podružnica Drinovci", "Vrsta ustanove": "javni dječji vrtić", "Adresa ustanove": "Središte 25, Drinovci", "Matična ustanova": "Grude", "Web-stranica": "https://www.instagram.com/djecjivrticgrude/", "Radno vrijeme": "pon.-pet.: 07:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3228081, 43.3606856 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2026.", "Naziv ustanove": "Dječji vrtić Grude, podružnica Gorica", "Vrsta ustanove": "javni dječji vrtić", "Adresa ustanove": "Jurinovac 11, Gorica", "Matična ustanova": "Grude", "Web-stranica": "https://www.instagram.com/djecjivrticgrude/", "Radno vrijeme": "pon.-pet.: 07:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.2866456, 43.4203998 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2010.", "Naziv ustanove": "Dječji vrtić Sunce", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Ulica hrvatskih branitelja 39, Grude", "Matična ustanova": "nema", "Web-stranica": "https://www.facebook.com/p/Dje%C4%8Dji-vrti%C4%87-Sunce-100057611433288/", "Radno vrijeme": "pon.-pet.: 07:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4233664, 43.364076 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2014.", "Naziv ustanove": "Dječji vrtić Pony", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Ulica Stjepana Radića 25, Grude", "Matična ustanova": "nema", "Web-stranica": "https://vrtic-pony.com/vrticpony/index.html", "Radno vrijeme": "pon.-pet.: 08:00-17:00; sub.: radi dvije mjesečno (kao radnim danima)" }, "geometry": { "type": "Point", "coordinates": [ 17.4121576, 43.369528 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2015.", "Naziv ustanove": "Dječji vrtić Kockica", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Ulica hrvatskih branitelja 41, Grude", "Matična ustanova": "nema", "Web-stranica": "https://www.facebook.com/p/Dje%C4%8Dji-vrti%C4%87-Kockica-100057608342987/", "Radno vrijeme": "pon.-pet.: 07:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4228597, 43.3641391 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2019.", "Naziv ustanove": "Dječji vrtić Hakuna Matata", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Ulica dr. Franje Tuđmana 26, Grude", "Matična ustanova": "nema", "Web-stranica": "https://www.instagram.com/hakunamatatagrude/", "Radno vrijeme": "pon.-pet.: 06:45-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4169032, 43.3703935 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2023.", "Naziv ustanove": "Dječji vrtić Sveti Filip Neri", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Ulica hrvatskih branitelja 52, Grude", "Matična ustanova": "nema", "Web-stranica": "https://www.facebook.com/p/Dje%C4%8Dji-vrti%C4%87-Sveti-Filip-Neri-Grude-100091133393336/", "Radno vrijeme": "pon.-pet.: 07:00-17:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4185857, 43.3619831 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2026.", "Naziv ustanove": "Dječji vrtić Grudvica", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Seline 18, Ružići", "Matična ustanova": "nema", "Web-stranica": "nema", "Radno vrijeme": "nepoznato" }, "geometry": { "type": "Point", "coordinates": [ 17.4263408, 43.3545464 ] } },
{ "type": "Feature", "properties": { "Godina osnutka": "2023.", "Naziv ustanove": "Dječji vrtić Smokvica", "Vrsta ustanove": "privatni dječji vrtić", "Adresa ustanove": "Ulica Andrijice Šimića 35, Grude", "Matična ustanova": "nema", "Web-stranica": "https://www.instagram.com/djecjivrtic_smokvica/", "Radno vrijeme": "nepoznato" }, "geometry": { "type": "Point", "coordinates": [ 17.4186235, 43.3720027 ] } }
]
}
