var zdravstveneustanove = {
"type": "FeatureCollection",
"name": "zdravstveneustanove",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Naziv ustanove": "Dom zdravlja Grude", "Adresa ustanove": "Ulica Mate Bobana 6, Grude", "Vrsta ustanove": "zdravstvena ustanova", "Nadležna ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Izvan radnog vremena i za hitne slučajeve dostupna je hitna pomoć koja se nalazi u prizemlju ustanove, na južnoj strani, u smjeru Radićeve ulice.", "Web-stranica": "https://dzgrude.com/", "Radno vrijeme": "pon.-pet.: 07:00-21:00; sub.: 07:00-14:00; ned.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4139158, 43.3717833 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ambulanta Drinovci", "Adresa ustanove": "Središte 35, Drinovci", "Vrsta ustanove": "zdravstvena ustanova", "Nadležna ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sve potrebne usluge koje ne daje ambulanta korisnik može potražiti u domu zdravlja Grude.", "Web-stranica": "https://dzgrude.com/", "Radno vrijeme": "pon.-pet: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3232323, 43.3605599 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ambulanta Sovići", "Adresa ustanove": "Dom 6, Sovići", "Vrsta ustanove": "zdravstvena ustanova", "Nadležna ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sve potrebne usluge koje ne daje ambulanta korisnik može potražiti u domu zdravlja Grude.", "Web-stranica": "https://dzgrude.com/", "Radno vrijeme": "pon.-pet: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3106271, 43.4135701 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Hitna pomoć Grude", "Adresa ustanove": "Ulica Mate Bobana 6, Grude", "Vrsta ustanove": "zdravstvena ustanova", "Nadležna ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Nalazi se u sklopu doma zdravlja Grude, na južnoj strani, u smjeru Radićeve ulice.", "Web-stranica": "https://dzgrude.com/", "Radno vrijeme": "pon.-ned.: 00:00-24:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4137248, 43.3717831 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Crveni križ Grude", "Adresa ustanove": "Ulica dr. Franje Tuđmana 83/C, Grude", "Vrsta ustanove": "humanitarna ustanova", "Nadležna ustanova": "Crveni križ ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sjedište organizacije nalazi se u Ljubuškom.", "Web-stranica": "https://www.ck-zzh.org/", "Radno vrijeme": "pon.-pet: 07:00-15:00; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.4201905, 43.3686224 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Fizio Apex", "Adresa ustanove": "Vlašići 63, Sovići", "Vrsta ustanove": "fizioterapeutska ustanova", "Nadležna ustanova": "privatna ustanova", "Razina uprave": "-", "Napomena": "-", "Web-stranica": "https://www.instagram.com/fizio_apex/", "Radno vrijeme": "pon.-pet.: 15:30-19:30; sub.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.3182764, 43.4092691 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Fizio Centar", "Adresa ustanove": "Ulica Gojka Šuška 40/A, Grude", "Vrsta ustanove": "fizioterapeutska ustanova", "Nadležna ustanova": "privatna ustanova", "Razina uprave": "-", "Napomena": "-", "Web-stranica": "https://www.fiziocentar.ba/", "Radno vrijeme": "pon.-pet.: 08:00-19:30; sub.: 08:00-12:00" }, "geometry": { "type": "Point", "coordinates": [ 17.4198303, 43.3730607 ] } },
{ "type": "Feature", "properties": { "Naziv ustanove": "Ambulanta Tihaljina", "Adresa ustanove": "Nezdravica 59, Tihaljina", "Vrsta ustanove": "zdravstvena ustanova", "Nadležna ustanova": "Ministarstvo zdravstva, rada, obitelji i socijalne politike ŽZH", "Razina uprave": "županijska razina", "Napomena": "Sve potrebne usluge koje ne daje ambulanta korisnik može potražiti u domu zdravlja Grude.", "Web-stranica": "https://dzgrude.com/", "Radno vrijeme": "sri., pet.: 07:30-10:30; pon., uto., čet.: ne radi" }, "geometry": { "type": "Point", "coordinates": [ 17.386422, 43.3148793 ] } }
]
}
